services:
  - type: web
    name: sous-api
    env: node
    buildCommand: pnpm install && pnpm turbo run build --filter=api
    startCommand: cd apps/api && pnpm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 20
